### ISSUE TITLE
References migration uses wrong field name

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#354]
I believe this needs to use `user_id` instead of `user`, unless this changed recently?

    mix phoenix.gen.model Video videos name:string approved_at:datetime description:text likes:integer views:integer user:references:users

**Comment by reklawnos** [comment]
This might give some insight into this issue. Following the tutorial and using
```
mix phoenix.gen.model Video videos name:string approved_at:datetime description:text likes:integer views:integer user:references:users
```
Works just fine, and using:
```
mix phoenix.gen.html Video videos name:string approved_at:datetime description:text likes:integer views:integer user_id:references:users
```
Works too, but using `phoenix.gen.html` and `user:references:users` instead causes these errors when running `mix test`:
```
Generated hello_phoenix app
.........

  1) test creates resource and redirects when data is valid (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:23
     ** (Postgrex.Error) ERROR (undefined_column): column "user_id" of relation "videos" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.model/5
       (ecto) lib/ecto/repo/model.ex:71: anonymous fn/11 in Ecto.Repo.Model.insert/4
       (ecto) lib/ecto/repo/model.ex:303: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
       (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
       (ecto) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.transaction/8
       (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:515: Ecto.Adapters.SQL.transaction/3



  2) test updates chosen resource and redirects when data is valid (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:52
     ** (Postgrex.Error) ERROR (undefined_column): column "user_id" of relation "videos" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.model/5
       (ecto) lib/ecto/repo/model.ex:71: anonymous fn/11 in Ecto.Repo.Model.insert/4
       (ecto) lib/ecto/repo/model.ex:303: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
       (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
       (ecto) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.transaction/8
       (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:515: Ecto.Adapters.SQL.transaction/3



  3) test shows chosen resource (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:34
     ** (Postgrex.Error) ERROR (undefined_column): column "user_id" of relation "videos" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.model/5
       (ecto) lib/ecto/repo/model.ex:71: anonymous fn/11 in Ecto.Repo.Model.insert/4
       (ecto) lib/ecto/repo/model.ex:303: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
       (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
       (ecto) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.transaction/8
       (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:515: Ecto.Adapters.SQL.transaction/3



  4) test deletes chosen resource (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:65
     ** (Postgrex.Error) ERROR (undefined_column): column "user_id" of relation "videos" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.model/5
       (ecto) lib/ecto/repo/model.ex:71: anonymous fn/11 in Ecto.Repo.Model.insert/4
       (ecto) lib/ecto/repo/model.ex:303: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
       (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
       (ecto) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.transaction/8
       (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:515: Ecto.Adapters.SQL.transaction/3



  5) test does not update chosen resource and renders errors when data is invalid (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:59
     ** (Postgrex.Error) ERROR (undefined_column): column "user_id" of relation "videos" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.model/5
       (ecto) lib/ecto/repo/model.ex:71: anonymous fn/11 in Ecto.Repo.Model.insert/4
       (ecto) lib/ecto/repo/model.ex:303: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
       (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
       (ecto) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.transaction/8
       (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:515: Ecto.Adapters.SQL.transaction/3



  6) test renders form for editing chosen resource (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:46
     ** (Postgrex.Error) ERROR (undefined_column): column "user_id" of relation "videos" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.model/5
       (ecto) lib/ecto/repo/model.ex:71: anonymous fn/11 in Ecto.Repo.Model.insert/4
       (ecto) lib/ecto/repo/model.ex:303: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
       (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
       (ecto) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.transaction/8
       (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:515: Ecto.Adapters.SQL.transaction/3



  7) test renders page not found when id is nonexistent (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:40
     Expected exception Ecto.NoResultsError but got Postgrex.Error (ERROR (undefined_column): column v0.user_id does not exist)
     stacktrace:
       test/controllers/video_controller_test.exs:41



  8) test lists all entries on index (HelloPhoenix.VideoControllerTest)
     test/controllers/video_controller_test.exs:13
     ** (Postgrex.Error) ERROR (undefined_column): column v0.user_id does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:450: Ecto.Adapters.SQL.execute/6
       (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
       (hello_phoenix) web/controllers/video_controller.ex:9: HelloPhoenix.VideoController.index/2
       (hello_phoenix) web/controllers/video_controller.ex:1: HelloPhoenix.VideoController.phoenix_controller_pipeline/2
       (hello_phoenix) lib/phoenix/router.ex:265: HelloPhoenix.Router.dispatch/2
       (hello_phoenix) web/router.ex:1: HelloPhoenix.Router.do_call/2

...........

Finished in 0.8 seconds (0.7s on load, 0.1s on tests)
28 tests, 8 failures
```

**Comment by lancehalvorsen** [comment]
This is fixed (changed to `user_id`) and pushed to phoenixframework.org.

@reklawnos, the generator and migration will "work" in that they won't throw errors, but they generate a column called `user` instead of `user_id` in the `videos` table. This will blow up whenever we try to use the Ecto associations, which will expect `user_id`.

Thanks for reporting!

**Comment by dreuter** [comment]
Couldn't this be captured at generation time?
Maybe just give a error message when the type is `*:references:*` and the field does not end with `_id`?

I was struggling with this today and it would be very convenient, if there was a error message (or at least a warning) at generation time for beginners like me.

Is there any case, where it would make sense to have a field not postfixed by `_id`?
