### ISSUE TITLE
Up And Running instructions not working

### ISSUE THREAD

**Issue by morenoh149** [phoenixframework/phoenix_guides#463]
Hi I'm very excited to get started with phoenix. I'm following the instructions at http://www.phoenixframework.org/docs/up-and-running

after running `mix phoenix.server` I get the following errors

```bash

[info] Running HelloPhoenix.Endpoint with Cowboy using http on port 4000
[info] Application hello_phoenix exited: HelloPhoenix.start(:normal, []) returned an error: shutdown: failed to start child: HelloPhoenix.Repo
    ** (EXIT) shutdown: failed to start child: Ecto.Adapters.Postgres
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not find Ecto.Adapters.Postgres.Connection.

Please verify you have added :postgrex as a dependency:

    {:postgrex, ">= 0.0.0"}

And remember to recompile Ecto afterwards by cleaning the current build:

    mix deps.clean ecto

                (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.start_link/4
                (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:326: :supervisor.start_children/3
                (stdlib) supervisor.erl:292: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
[info] Application postgrex exited: :stopped
[info] Application db_connection exited: :stopped
[info] Application backoff exited: :stopped
[info] Application connection exited: :stopped
[info] Application phoenix_ecto exited: :stopped
[info] Application ecto exited: :stopped

=INFO REPORT==== 21-Jan-2016::19:04:23 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application hello_phoenix: HelloPhoenix.start(:normal, []) returned an error: shutdown: failed to start child: HelloPhoenix.Repo
    ** (EXIT) shutdown: failed to start child: Ecto.Adapters.Postgres
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not find Ecto.Adapters.Postgres.Connection.

Please verify you have added :postgrex as a dependency:

    {:postgrex, ">= 0.0.0"}

And remember to recompile Ecto afterwards by cleaning the current build:

    mix deps.clean ecto

                (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.start_link/4
                (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:326: :supervisor.start_children/3
                (stdlib) supervisor.erl:292: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
I think this is pretty high priority as it's the first thing I new user does with phoenix

**Comment by morenoh149** [comment]
I have run `mix ecto.create` and it runs successfully.

**Comment by arthurcolle** [comment]
mine still didn't work after a `mix ecto.create` fwiw, but I found out my psql wasn't on my path, but still, the default project should definitely build/work even without a working db connection, it's just serving static files after all

**Comment by chrismccord** [comment]
The temporary workaround until we can push a new Ecto version tomorrow is to lock your postgrex version in mix.exs as:

    {:postgrex, "0.10.0"}

Then run `mix deps.update postgrex.

**Comment by morenoh149** [comment]
following the guide now works :+1:
